"""about me last seen

Revision ID: 07782388b438
Revises: 03da7c2eb59c
Create Date: 2020-05-21 14:43:51.320668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07782388b438'
down_revision = '03da7c2eb59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
