"""post comments

Revision ID: d74d557fbab9
Revises: 3e96c6c4daf0
Create Date: 2020-06-05 23:15:32.632243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74d557fbab9'
down_revision = '3e96c6c4daf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('comment_key', 'post', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('comment_key', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
